### ISSUE TITLE
/src/zero/NoteEncryption.cpp

### ISSUE THREAD

**Issue by zerZERCer** [LEAD-Anoy74/ZeroClassic#1]
I noticed you made this change to the NoteEncryption code. I think this may have unintended side effects. I think it might be advisable to change it back to retain full compatibility with the original zero nodes and chain.

Line 35:   
  memcpy(personalization, "ZeroKDF", 8);

  memcpy(personalization, "ZcashKDF", 8);

**Comment by LEAD-Anoy74** [comment]
After some double checks under the hoods, we confirm that can be left as is. No issues regarding this pararameters, reopening in case of troubles.
